const seed={subjects:[{id:1,name:'Pedagogia generale',teacher:'',color:'#8d67d8'}],files:[],lessons:[],exams:[]};
let db=JSON.parse(localStorage.getItem('sfp15')||'null')||seed;let pendingLesson=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('sfp15',JSON.stringify(db));renderAll()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const b=$(`#nav button[data-view="${v}"]`);$('#pageTitle').textContent=b?b.textContent.replace(/^[^ ]+ /,''):v}
$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderAll(){
 $('#statSubjects').textContent=db.subjects.length;$('#statLessons').textContent=db.lessons.length;$('#statFiles').textContent=db.files.length;
 const upcoming=[...db.exams].filter(e=>new Date(e.date)>=new Date(new Date().toDateString())).sort((a,b)=>new Date(a.date)-new Date(b.date))[0];
 if(upcoming){const d=Math.ceil((new Date(upcoming.date)-new Date())/86400000);$('#statExam').textContent=d+'g';$('#statExamName').textContent=upcoming.name}else{$('#statExam').textContent='—';$('#statExamName').textContent='da pianificare'}
 const total=Math.max(db.lessons.length+db.exams.length,1),done=db.lessons.length+db.exams.filter(e=>e.done).length,p=Math.min(100,Math.round(done/Math.max(total,4)*100));$('#progressLabel').textContent=p+'%';$('#progressBar').style.width=p+'%';
 $('#nextActivities').innerHTML=db.exams.length?db.exams.slice().sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(0,3).map(e=>`<div class="listItem"><div><strong>${esc(e.name)}</strong><div class="meta">${new Date(e.date).toLocaleDateString('it-IT')} · ${esc(e.subject||'Materia non indicata')}</div></div><span>${e.done?'✓':'◷'}</span></div>`).join(''):'Aggiungi un esame per creare il tuo piano.';
 $('#subjectsGrid').innerHTML=db.subjects.length?db.subjects.map(s=>`<article class="card subjectCard"><h3><i class="dot" style="background:${s.color||'#8d67d8'}"></i>${esc(s.name)}</h3><p class="muted">${esc(s.teacher||'Docente non indicato')}</p><footer><span>${db.lessons.filter(l=>l.subject===s.name).length} lezioni</span><button onclick="removeSubject(${s.id})">Rimuovi</button></footer></article>`).join(''):'<div class="empty">Nessuna materia ancora.</div>';
 $('#lessonSubject').innerHTML=db.subjects.map(s=>`<option>${esc(s.name)}</option>`).join('');
 $('#filesList').innerHTML=db.files.length?db.files.map(f=>`<div class="listItem"><div><strong>📄 ${esc(f.name)}</strong><div class="meta">${esc(f.type||'file')} · ${f.size}</div></div><button onclick="removeFile(${f.id})">Rimuovi</button></div>`).join(''):'<div class="empty">Nessun materiale caricato.</div>';
 $('#manualContent').innerHTML=db.lessons.length?`<h2>Manuale SFP Study di Sofia</h2>${db.lessons.map((l,i)=>`<article><small>Capitolo ${i+1} · ${esc(l.subject)} · ${l.date}</small><h3>${esc(l.topic)}</h3><p><strong>Obiettivo:</strong> ${esc(l.goal)}</p><p>${esc(l.body)}</p><p><strong>Punti chiave:</strong> ${l.points.map(esc).join(' • ')}</p></article>`).join('')}`:'<div class="empty">Le lezioni salvate verranno raccolte automaticamente nel manuale.</div>';
 $('#registerList').innerHTML=db.lessons.length?db.lessons.slice().reverse().map(l=>`<div class="listItem"><div><strong>${esc(l.topic)}</strong><div class="meta">${esc(l.subject)} · ${l.date} · completata</div></div><span>✓</span></div>`).join(''):'<div class="empty">Il registro è ancora vuoto.</div>';
 $('#examsList').innerHTML=db.exams.length?db.exams.map(e=>`<div class="listItem"><div><strong>${esc(e.name)}</strong><div class="meta">${esc(e.subject||'')} · ${new Date(e.date).toLocaleDateString('it-IT')} · ${esc(e.priority)}</div></div><button onclick="toggleExam(${e.id})">${e.done?'Riapri':'Completa'}</button></div>`).join(''):'<div class="empty">Nessun esame pianificato.</div>';
}
window.removeSubject=id=>{db.subjects=db.subjects.filter(x=>x.id!==id);save()};window.removeFile=id=>{db.files=db.files.filter(x=>x.id!==id);save()};window.toggleExam=id=>{const e=db.exams.find(x=>x.id===id);e.done=!e.done;save()};
function modal(type){const d=$('#modal'),f=$('#modalFields');d.dataset.type=type;if(type==='subject'){ $('#modalTitle').textContent='Nuova materia';f.innerHTML='<label>Nome<input name="name" required placeholder="Es. Psicologia dello sviluppo"></label><label>Docente<input name="teacher" placeholder="Facoltativo"></label>'}else{$('#modalTitle').textContent='Aggiungi esame';f.innerHTML=`<label>Esame<input name="name" required></label><label>Materia<select name="subject">${db.subjects.map(s=>`<option>${esc(s.name)}</option>`).join('')}</select></label><label>Data<input type="date" name="date" required></label><label>Priorità<select name="priority"><option>Alta</option><option selected>Media</option><option>Bassa</option></select></label>`}d.showModal()}
$('#addSubject').onclick=()=>modal('subject');$('#addExam').onclick=()=>modal('exam');
$('#modalForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return; e.preventDefault();const fd=new FormData(e.target);if($('#modal').dataset.type==='subject')db.subjects.push({id:Date.now(),name:fd.get('name'),teacher:fd.get('teacher'),color:'#8d67d8'});else db.exams.push({id:Date.now(),name:fd.get('name'),subject:fd.get('subject'),date:fd.get('date'),priority:fd.get('priority'),done:false});save();$('#modal').close();toast('Salvato')};
$('#fileInput').onchange=e=>{[...e.target.files].forEach(f=>db.files.push({id:Date.now()+Math.random(),name:f.name,type:f.type,size:(f.size/1024/1024).toFixed(2)+' MB'}));save();toast('Materiali aggiunti')};
$('#generateLesson').onclick=()=>{const subject=$('#lessonSubject').value,topic=$('#lessonTopic').value.trim(),goal=$('#lessonGoal').value.trim();if(!topic)return toast('Inserisci un argomento');const points=[`Definizione e contesto di ${topic}`,`Concetti fondamentali e collegamenti`, `Applicazioni nella scuola primaria`, `Domande utili per il ripasso`];pendingLesson={id:Date.now(),subject,topic,goal:goal||`Comprendere e ripassare ${topic}`,date:new Date().toLocaleDateString('it-IT'),body:`Questa lezione introduce ${topic} con un percorso graduale: prima il quadro generale, poi i concetti essenziali e infine il collegamento con la pratica educativa. Il contenuto può essere ampliato usando i materiali caricati nella materia.`,points};$('#lessonPreview').innerHTML=`<section><small>${esc(subject)}</small><h3>${esc(topic)}</h3><p><strong>Obiettivo</strong><br>${esc(pendingLesson.goal)}</p></section><section><h3>Spiegazione</h3><p>${esc(pendingLesson.body)}</p></section><section><h3>Punti chiave</h3><ul>${points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></section><button class="primary" id="completeLesson">Completa e sincronizza</button>`;$('#completeLesson').onclick=()=>{db.lessons.push(pendingLesson);pendingLesson=null;save();toast('Lezione aggiunta a manuale e registro');go('registro')}};
$('#exportManual').onclick=()=>{const text=db.lessons.map((l,i)=>`CAPITOLO ${i+1} - ${l.topic}\nMateria: ${l.subject}\nObiettivo: ${l.goal}\n\n${l.body}\n\nPunti chiave:\n- ${l.points.join('\n- ')}\n`).join('\n----------------\n\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text||'Manuale vuoto'],{type:'text/plain'}));a.download='SFP-Study-Manuale.txt';a.click();URL.revokeObjectURL(a.href)};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('sfpTheme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('sfpTheme')==='dark')document.body.classList.add('dark');
setInterval(()=>{const s=document.createElement('span');s.className='star';s.textContent=Math.random()>.5?'✦':'✧';s.style.left=Math.random()*100+'vw';s.style.bottom='-20px';s.style.fontSize=10+Math.random()*18+'px';document.querySelector('.stars').appendChild(s);setTimeout(()=>s.remove(),7000)},800);
renderAll();
